addEvent("dpDriftPoints.earnedPoints", true)
addEventHandler("dpDriftPoints.earnedPoints", resourceRoot, function (points)
	local driftMoney = exports.dpShared:getEconomicsProperty("drift_money")
	money = math.floor(points / 1000 * driftMoney)
	exports.dpCore:givePlayerMoney(client, money)
end)