maps = {
    yz_circuit = {
        { src = "yz.txd",  model = 1940 },
        { src = "yz1.dff",  model = 1940 },
        { src = "yz1.col",  model = 1940 },
        { src = "yz.txd",  model = 1941 },
        { src = "yz2.dff",  model = 1941 },
        { src = "yz2.col",  model = 1941 },
        { src = "yz.txd",  model = 1942 },
        { src = "yz3.dff",  model = 1942 },
        { src = "yz3.col",  model = 1942 },
    },


    project_touge = {
        { src = "springshorse.txd", model = 1937 },
        { src = "projectouge.dff",  model = 1937 },
        { src = "springshorse.col", model = 1937 },
    },

    mikawa = {
        { src = "mikawa.txd", model = 1932 },
        { src = "mikawa.txd", model = 1933 },
        { src = "mikawa.txd", model = 1934 },
        { src = "mikawa.txd", model = 1935 },
        { src = "mikawa1.col", model = 1932 },
        { src = "mikawa2.col", model = 1933 },
        { src = "mikawa3.col", model = 1934 },
        { src = "mikawa4.col", model = 1935 },
        { src = "mikawa1.dff", model = 1932 },
        { src = "mikawa2.dff", model = 1933 },
        { src = "mikawa3.dff", model = 1934 },
        { src = "mikawa4.dff", model = 1935 },        
    },

    mazda_raceway = {
        { src = "sega.txd", model = 1910 },
        { src = "sega.txd", model = 1911 },
        { src = "sega.txd", model = 1912 },
        { src = "sega.txd", model = 1913 },
        { src = "sega.txd", model = 1914 },
        { src = "sega.txd", model = 1915 },
        { src = "sega.txd", model = 1916 },
        { src = "sega.txd", model = 1917 },
        { src = "sega.txd", model = 1918 },
        { src = "sega.txd", model = 1919 },
        { src = "sega.txd", model = 1920 },
        { src = "sega.txd", model = 1921 },
        { src = "sega.txd", model = 1922 },
        { src = "sega.txd", model = 1923 },
        { src = "sega.txd", model = 1924 },
        { src = "sega.txd", model = 1925 },
        { src = "sega.txd", model = 1926 },

        { src = "sega1.dff", model = 1910 },
        { src = "sega2.dff", model = 1911 },
        { src = "sega3.dff", model = 1912 },
        { src = "sega4.dff", model = 1913 },
        { src = "sega5.dff", model = 1914 },
        { src = "sega6.dff", model = 1915 },
        { src = "sega7.dff", model = 1916 },
        { src = "sega8.dff", model = 1917 },
        { src = "sega9.dff", model = 1918 },
        { src = "sega10.dff", model = 1919 },
        { src = "sega11.dff", model = 1920 },
        { src = "sega12.dff", model = 1921 },
        { src = "sega13.dff", model = 1922 },
        { src = "sega14.dff", model = 1923 },
        { src = "sega15.dff", model = 1924 },
        { src = "sega16.dff", model = 1925 },
        { src = "sega17.dff", model = 1926 },

        { src = "sega1.col", model = 1910 },
        { src = "sega2.col", model = 1911 },
        { src = "sega3.col", model = 1912},
        { src = "sega4.col", model = 1913 },
        { src = "sega5.col", model = 1914 },
        { src = "sega6.col", model = 1915 },
        { src = "sega7.col", model = 1916 },
        { src = "sega8.col", model = 1917 },
        { src = "sega9.col", model = 1918 },
        { src = "sega10.col", model = 1919 },
        { src = "sega11.col", model = 1920 },
        { src = "sega12.col", model = 1921 },
        { src = "sega13.col", model = 1922 },
        { src = "sega14.col", model = 1923 },
        { src = "sega15.col", model = 1924 },
        { src = "sega16.col", model = 1925 },    
        { src = "sega17.col", model = 1926 },  		
    },

    hero_shinoi = {
        { src = "heroshinoi.txd", model = 2033 },
        { src = "heroshinoi.txd", model = 2034 },
        { src = "heroshinoi.txd", model = 2035 },
        { src = "heroshinoi1.dff", model = 2033 },
        { src = "heroshinoi2.dff", model = 2034 },
        { src = "heroshinoi3.dff", model = 2035 },
        { src = "heroshinoi1.col", model = 2033 },
        { src = "heroshinoi2.col", model = 2034 },
        { src = "heroshinoi3.col", model = 2035 },                
    },

    honjo_circuit = {
        { src = "honjo.txd", model = 2347 },
        { src = "honjo.txd", model = 2348 },
        { src = "honjo.txd", model = 2349 },
        { src = "honjo.txd", model = 2327 },
        { src = "honjo1.dff", model = 2347 },
        { src = "honjo2.dff", model = 2348 },
        { src = "honjo3.dff", model = 2349 },
        { src = "honjo4.dff", model = 2327 },
        { src = "honjo1.col", model = 2347 },
        { src = "honjo2.col", model = 2348 },
        { src = "honjo3.col", model = 2349 },
        { src = "honjo4.col", model = 2327 },
    },

    gateway_raceway = {
        { src = "gateway.txd", model = 1905 },
        { src = "gateway.txd", model = 1906 },
        { src = "gateway.txd", model = 1907 },
        { src = "gateway.txd", model = 1908 },
        { src = "gateway.txd", model = 1909 },
        { src = "gateway1.dff", model = 1905 },
        { src = "gateway2.dff", model = 1906 },
        { src = "gateway3.dff", model = 1907 },
        { src = "gateway4.dff", model = 1908 },
        { src = "gateway5.dff", model = 1909 },
        { src = "gateway1.col", model = 1905},
        { src = "gateway2.col", model = 1906 },
        { src = "gateway3.col", model = 1907 },
        { src = "gateway4.col", model = 1908 },
        { src = "gateway5.col", model = 1909 },
    },

    gokart2 = {
        { src = "gokart.txd", model = 1576 },
        { src = "gokart.txd", model = 1577 },
        { src = "gokart.txd", model = 1578 },
        { src = "gokart.txd", model = 1579 },
        { src = "gokart1.dff", model = 1576 },
        { src = "gokart2.dff", model = 1577 },
        { src = "gokart3.dff", model = 1578 },
        { src = "gokart4.dff", model = 1579 },
        { src = "gokart1.col", model = 1576 },
        { src = "gokart2.col", model = 1577 },
        { src = "gokart3.col", model = 1578 },
        { src = "gokart4.col", model = 1579 },
    },

    ebisu_west = {
        { src = "ebiwest.txd", model = 1927 },
        { src = "ebiwest.txd", model = 1928 },
        { src = "ebiwest.txd", model = 1929 },
        { src = "ebiwest.txd", model = 1930 },
        { src = "ebiwest.txd", model = 1931 },

        { src = "ebiwest1.dff", model = 1927 },
        { src = "ebiwest2.dff", model = 1928 },
        { src = "ebiwest3.dff", model = 1929 },
        { src = "ebiwest4.dff", model = 1930 },
        { src = "ebiwest5.dff", model = 1931 },

        { src = "ebiwest1.col", model = 1927 },
        { src = "ebiwest2.col", model = 1928 },
        { src = "ebiwest3.col", model = 1929 },
        { src = "ebiwest4.col", model = 1930 },
        { src = "ebiwest5.col", model = 1931 },
    },

    galdori = {
        { src = "galdori.txd", model = 14566 },
        { src = "galdori.txd", model = 14567 },
        { src = "galdori.dff", model = 14566 },
        { src = "galdori1.dff", model = 14567 },
        { src = "galdori.col", model = 14566 },     
        { src = "galdori1.col", model = 14567 },        

    },
	
    bihoku = {
        { src = "bihoku.txd", model = 1943 },
        { src = "bihoku.txd", model = 1944 },
        { src = "bihoku.txd", model = 1945 },
        { src = "bihoku1.dff", model = 1943 },
        { src = "bihoku2.dff", model = 1944 },
        { src = "bihokutree.dff", model = 1945 },
        { src = "bihoku1.col", model = 1943 },
        { src = "bihoku2.col", model = 1944 },     
        { src = "bihokutree.col", model = 1945 },        

    },
	
    unost = {
        { src = "unost.txd", model = 2171 },
        { src = "unost.txd", model = 2172 },
        { src = "unost.txd", model = 2173 },
        { src = "unost.txd", model = 2174 },
        { src = "unost.txd", model = 2175 },
        { src = "unost.dff", model = 2171 },
        { src = "unost2.dff", model = 2172 },
        { src = "unost3.dff", model = 2173 },
        { src = "unost4.dff", model = 2174 },
        { src = "unost5.dff", model = 2175 },
        { src = "unost.col", model = 2171 },
        { src = "unost2.col", model = 2172 },     
        { src = "unost3.col", model = 2173 },
        { src = "unost4.col", model = 2174 },     
        { src = "unost5.col", model = 2175 },               

    },

    winter_rally_race_track = {
        { src = "rally.txd", model = 1835 },
        { src = "rally.txd", model = 1836 },
        { src = "rally.txd", model = 1837 },
        { src = "rally.txd", model = 1838 },
        { src = "rally.txd", model = 1851 },
        { src = "rally.txd", model = 1852 },
        { src = "rally1.dff", model = 1835 },
        { src = "rally2.dff", model = 1836 },
        { src = "rally3.dff", model = 1837 },
        { src = "rally4.dff", model = 1838 },
        { src = "rally5.dff", model = 1851 },
        { src = "rally6.dff", model = 1852 },
        { src = "rally1.col", model = 1835 },
        { src = "rally2.col", model = 1836 },     
        { src = "rally3.col", model = 1837 },        
        { src = "rally4.col", model = 1838 },
        { src = "rally5.col", model = 1851 },     
        { src = "rally6.col", model = 1852 },      
   }	
}