addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('1.txd',true)
engineImportTXD(txd, 1833)
local dff = engineLoadDFF('1.dff', 0)
engineReplaceModel(dff, 1833)
local col = engineLoadCOL('1.col')
engineReplaceCOL(col, 1833)
engineSetModelLODDistance(1833, 150)
end)

addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('2.txd',true)
engineImportTXD(txd, 4186)
local dff = engineLoadDFF('2.dff', 0)
engineReplaceModel(dff, 4186)
local col = engineLoadCOL('2.col')
engineReplaceCOL(col, 4186)
engineSetModelLODDistance(4186, 150)
end)

addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('3.txd',true)
engineImportTXD(txd, 1834)
local dff = engineLoadDFF('3.dff', 0)
engineReplaceModel(dff, 1834)
local col = engineLoadCOL('3.col')
engineReplaceCOL(col, 1834)
engineSetModelLODDistance(1834, 150)
end)

addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('4.txd',true)
engineImportTXD(txd, 14567)
local dff = engineLoadDFF('4.dff', 0)
engineReplaceModel(dff, 14567)
local col = engineLoadCOL('4.col')
engineReplaceCOL(col, 14567)
engineSetModelLODDistance(14567, 1000)
end)